### ISSUE TITLE
PDF Issue

### ISSUE THREAD

**Issue by Elaoed** [miyakogi/pyppeteer#100]
Hi. It's me again. :)
        Today i encounter with a problem in page.pdf().  pdf() works with single page. but if i want to put two screenshot in one pdf file. something wrong occur, only on page will appear. My code is show in below

> buffer1 = await page.pdf(scale=0.8)
> buffers.append(buffer1)
> print(len(buffer1))
> buffer2 = await page.pdf(scale=0.8)
> buffers.append(buffer1)
> print(len(buffer1))
> buffers = (b'' * 3).join([x for x in reversed(buffers)])
> print(len(buffers))
> with open('/tmp/a.pdf', 'wb') as f:
>     f.write(buffers)

length of different buffers show in console is correct, but the result is only one picture shows in pdf file.
By the way. how to create a pdf file with two pages :)

**Comment by miyakogi** [comment]
Merging pdf pages is not a pyppeteer's matter.
Please use proper library to manipulate pdf files.
