### ISSUE TITLE
implement request.isNavigationRequest in pyppeteer v0.0.19

### ISSUE THREAD

**Issue by tigerfsh** [miyakogi/pyppeteer#102]
request.isNavigationRequest is new in pupeteer v1.5.0, how to Implement the same logical function in pyppeteer v0.0.19? Advise wanted!

**Comment by miyakogi** [comment]
This is the puppeteer's commit implementing `isNavigationRequest` method.
https://github.com/GoogleChrome/puppeteer/commit/724fa512cf8b234ff594e41f273799a1900a9f95

To implement the same function, maybe needs to patch pyppeteer itself.
I'm not sure, but `Request.resourceType == 'document'` might be able to emulate similar function.
