### ISSUE TITLE
Failed to connect to port

### ISSUE THREAD

**Issue by PeterGardas** [miyakogi/pyppeteer#104]
Good morning
I just installed newest version of pyppeteer from github but when i try to run the sample code that should take screenshots it thows this exception at me : 

`Traceback (most recent call last):
  File "take_screenshot.py", line 11, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "take_screenshot.py", line 5, in main
    browser = await launch()
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 257, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 168, in launch
    self.browserWSEndpoint = self._get_ws_endpoint()
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 186, in _get_ws_endpoint
    raise BrowserError(f'Failed to connect to browser port: {url}')
pyppeteer.errors.BrowserError: Failed to connect to browser port: http://127.0.0.1:53359/json/version
`

I ran the `netstat -tulpn` command which bassicaly spits out all the ports your PC is listening to or using and this is the output:

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    

tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      1055/smbd           
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      1055/smbd           
tcp6       0      0 :::445                  :::*                    LISTEN      1055/smbd           
tcp6       0      0 :::139                  :::*                    LISTEN      1055/smbd           
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           9786/chrome         
udp        0      0 0.0.0.0:68              0.0.0.0:*                           913/dhclient        
udp        0      0 10.0.50.255:137         0.0.0.0:*                           841/nmbd            
udp        0      0 10.0.50.15:137          0.0.0.0:*                           841/nmbd            
udp        0      0 0.0.0.0:137             0.0.0.0:*                           841/nmbd            
udp        0      0 10.0.50.255:138         0.0.0.0:*                           841/nmbd            
udp        0      0 10.0.50.15:138          0.0.0.0:*                           841/nmbd            
udp        0      0 0.0.0.0:138             0.0.0.0:*                           841/nmbd            
udp6       0      0 :::5353                 :::*                                9786/chrome 

So there is no process using or listening to port 53359 so where is the problem?

OS : ParrotOS 
Python : Python3.6.5
pyppeteer : Newest 11.7.2018

**Comment by miyakogi** [comment]
Maybe failing to start chromium.
Could you start bundled chromium manually?
If it fails, please try to add `--no-sandbox` argument to launch function:

```python
browser = await launch(args=['--no-sandbox'])
```

See also https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-fails-due-to-sandbox-issues

**Comment by PeterGardas** [comment]
Thank you, that worked out :D .
