### ISSUE TITLE
How to kill process friendly

### ISSUE THREAD

**Issue by Germey** [miyakogi/pyppeteer#105]
Hi, I've used pyppeteer in Scrapy as Download Middleware. But I find that it's difficult to stop the running Scrapy Project.

When I press 'Ctrl + C', the console will print this for per time. I press once, it prints once and never stop.

Like this:

```
2018-07-13 02:58:09 [asyncio] ERROR: Task exception was never retrieved
future: <Task finished coro=<Connection._async_send() done, defined at /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyppeteer/connection.py:61> exception=ConnectionClosed('WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason',)>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyppeteer/connection.py", line 64, in _async_send
    await self.connection.send(msg)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/websockets/protocol.py", line 334, in send
    yield from self.ensure_open()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/websockets/protocol.py", line 470, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
```

I tried to except this exception in Download Middleware but it doesn't work.

and the `__del__` function doesn't work too:

```
    def __del__(self):
        self.loop.close()
```

Here is my code:

[https://github.com/Python3WebSpider/ScrapyCrawlSpider](https://github.com/Python3WebSpider/ScrapyCrawlSpider)

and this is my Download Middleware: 

[https://github.com/Python3WebSpider/ScrapyCrawlSpider/blob/master/scrapycrawlspider/middlewares.py](https://github.com/Python3WebSpider/ScrapyCrawlSpider/blob/master/scrapycrawlspider/middlewares.py)

you can run it with `scrapy crawl china` after installing the requirements.

Now I can't stop the Scrapy Project as usual, I wonder how to make it more friendly to stop the Project.

Hope you can help me, thanks~

**Comment by miyakogi** [comment]
Thank you for reporting issue.
Maybe this is caused by the same reason which is reported in https://github.com/miyakogi/pyppeteer/issues/78.

I will try to fix it.

**Comment by miyakogi** [comment]
Could you try with these options?

```python
            pyppeteer.launch(
                headless=True,
                handleSIGTERM=False,
                handleSIGINT=False,
            ))
```

**Comment by Germey** [comment]
unfortunately, it still doesn't work.

But it won't print error for each `ctrl + c`, it only print the error once and the whole project is suspended.

like this:

```
2018-07-13 17:01:52 [scrapycrawlspider.middlewares] DEBUG: rendering http://tech.china.com/article/20180530/20180530145378.html
^C2018-07-13 17:01:56 [scrapy.crawler] INFO: Received SIG_UNBLOCK, shutting down gracefully. Send again to force 
^C2018-07-13 17:01:57 [scrapy.crawler] INFO: Received SIG_UNBLOCK twice, forcing unclean shutdown
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C2018-07-13 17:02:00 [asyncio] ERROR: Task exception was never retrieved
future: <Task finished coro=<Connection._async_send() done, defined at /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyppeteer/connection.py:61> exception=ConnectionClosed('WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason',)>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyppeteer/connection.py", line 64, in _async_send
    await self.connection.send(msg)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/websockets/protocol.py", line 334, in send
    yield from self.ensure_open()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/websockets/protocol.py", line 470, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

the console is suspended and will not output any information.

**Comment by Germey** [comment]
this is my newest code of download middleware: [https://github.com/Python3WebSpider/ScrapyCrawlSpider/blob/master/scrapycrawlspider/middlewares.py](https://github.com/Python3WebSpider/ScrapyCrawlSpider/blob/master/scrapycrawlspider/middlewares.py)

**Comment by miyakogi** [comment]
hmm...

Unfortunately, regardless of these options, this issue is not reproduced on my environment (linux).
What OS are you using?

**Comment by Germey** [comment]
Phatform: OSX 10.13.3
Python: 3.6.1
Pyppeteer: 0.0.19
Scrapy: 1.4.0

**Comment by miyakogi** [comment]
OK, thanks.
Could you try with the latest `dev` branch?
```
pip install -U git+git://github.com/miyakogi/pyppeteer@dev
```

**Comment by Germey** [comment]
It works!
I can kill the process smoothly, thanks for your help.

By the way, what's the major solution of it? I didn't find the solution which copes with this issue from your recent update.

**Comment by miyakogi** [comment]
Maybe thanks to these @scp10011 's commits (https://github.com/miyakogi/pyppeteer/pull/90, https://github.com/miyakogi/pyppeteer/pull/91).

**Comment by Germey** [comment]
Thanks~
