### ISSUE TITLE
"node.click()" or "node.tap()" doesn't work for "a" html tag that has long text and auto-wrap

### ISSUE THREAD

**Issue by csugzq** [miyakogi/pyppeteer#111]
It's weird when I try to click a "a" tag that has long text from page and it doesn't work. But for a short "a" tag, it does work. Have anyone ever been in this situation?

**Comment by miyakogi** [comment]
Sorry for late response.
I reproduced this issue.
It seems to be a bug.

Workaround is:

```python
element = await page.querySelector('a')  # or any proper selector
await page.evaluate('(element) => element.click()', element)
```

**Comment by miyakogi** [comment]
This is a bug of puppeteer fixed in puppeteer v1.6.0, but pyppeteer does not catch up yet, sorry.

**Comment by csugzq** [comment]
@miyakogi Thanks

**Comment by miyakogi** [comment]
Pyppeteer 0.0.24 caught up puppeteer v1.6.0 and now fixed this issue.
