### ISSUE TITLE
Posting a username and password Error

### ISSUE THREAD

**Issue by amarksnj** [miyakogi/pyppeteer#114]
async def Login(page):
    
    userTextBox = await page.querySelectorAll('USER')
    passwordTextBox = await page.querySelectorAll('PASSWRD')
    userTextBox.type(Username) 
    passwordTextBox.type(Password)                               
    loginButton = page.querySelectorAll('Enter') 
    loginButton.tap()

I get the error  " userTextBox.type(Username), AttributeError: 'list' object has no attribute 'type'      "

**Comment by miyakogi** [comment]
`page.querySelectorAll` returns list of all elements which matches selector.
Please use `page.querySelector` instead.
