### ISSUE TITLE
Browser does not start in Docker

### ISSUE THREAD

**Issue by scythargon** [miyakogi/pyppeteer#14]
Hello and thank you for your awesome package!
I tried it locally on my ubuntu, liked it a lot, now trying to add it to my project's intergration testing facilities and experiencing basically the next minified issue:
![image](https://user-images.githubusercontent.com/1755870/33514657-d1d9f936-d768-11e7-8a77-ea5986f309db.png)

I guess it might require installation of some additional Debian (because `python:3.6` docker image is based on Debian 8) packages or env variables but I don't know which ones exactly.

Please help me:)

**Comment by scythargon** [comment]
Figured it out myself. 

Compiled from many sources:

1) It was required to install chrome like this:
```
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
  gnupg \
    --no-install-recommends \
    && curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
    && apt-get update && apt-get install -y \
    google-chrome-stable \
    --no-install-recommends

# It won't run from the root user.
RUN groupadd chrome && useradd -g chrome -s /bin/bash -G audio,video chrome \
    && mkdir -p /home/chrome && chown -R chrome:chrome /home/chrome
```

2) It could not be run from a root user - we just created a `chrome` user above.

3) I had to update my docker-compose.yml file version from `2.1` to `3.3` May be some lower will be fine too, but I needed to add
```
    cap_add:
      - SYS_ADMIN
``` 
to my container.

**Comment by davepeck** [comment]
@scythargon Are there must be missing steps in your "solution"? `Pyppeteer` has code that explicitly ties it to its own download/install of chromium; it's not clear to me why your approach, as described, would work.

**Comment by scythargon** [comment]
@davepeck If the main process in the Docker container is run by the root user (which is the most common approach) and it tries to spawn Chrome process - I believe you gonna be fucked. 

That's the first point. 

Second one - it is much better idea to download chrome at the stage of the Docker image creation so it will be cached and you won't have to redo that every time you start your Docker container (if, of course, you haven't configured your shared volumes which is way less straightforward than what I did).

So yes, this is my "Solution" to these two problems.

**Comment by davepeck** [comment]
@scythargon -- thanks. Understood about (1) the root user, and (2) the desirability of downloading chromium when creating your docker image -- those are both good points! 

That said, I still don't understand how `pyppeteer` is finding the copy of chromium you installed in your Docker image; my read of `chromium_downloader.py` makes me think that it won't find your install, and will happily go off and install its own copy _anyway_. Perhaps I'm missing something here?

**Comment by scythargon** [comment]
@davepeck Sure you do:)
```
from pyppeteer import launch
browser = launch(executablePath='/usr/bin/google-chrome-stable')
page = await browser.newPage()
```
It definitely uses this chrome executable.

**Comment by davepeck** [comment]
@scythargon Ah, that's the missing piece!. You _explicitly pointed pyppeteer to your own install of chromium_; you didn't mention that in your original post, and I was unaware this was even possible. Thanks for the clarification.

**Comment by scythargon** [comment]
The pyppeteer docs are lacking a bit, it is a good idea to also look into the original pUppeteer ones.
