### ISSUE TITLE
how to use cdn to download chromium  

### ISSUE THREAD

**Issue by iloveyo123u1** [miyakogi/pyppeteer#141]
hi, there

when i run   `pyppeteer-install`,  i wait long time,  but it not downloaded

i want use cdn to donwload chromium,

like this `npm config set puppeteer_download_host=https://storage.googleapis.com.cnpmjs.org`

can you help me ?

thank you very much

**Comment by miyakogi** [comment]
Please use `$PYPPETEER_DOWNLOAD_HOST` environment variable.
See https://miyakogi.github.io/pyppeteer/reference.html#environment-variables
