### ISSUE TITLE
Getting some unhandled exceptions

### ISSUE THREAD

**Issue by scythargon** [miyakogi/pyppeteer#15]
Whenever the script or python interactive console where I use your library quits.

![image](https://user-images.githubusercontent.com/1755870/33530895-dbf2f9e8-d896-11e7-89c7-c51394c7a115.png)

**Comment by alexadusei** [comment]
I'm getting the same problem. Works in terminal for me, but not through a scripted definition call in a saved .py file

**Comment by scythargon** [comment]
@alexadusei Hello, Alex! Unfortunately I haven't found a solution for this, but seems like it does not hurt the execution apart from making the logs dirty.

**Comment by alexadusei** [comment]
@scythargon Hello! That's good to hear, I've noticed that too. Hopefully it's resolved sometime down the line!

**Comment by miyakogi** [comment]
Same as https://github.com/miyakogi/pyppeteer/issues/24
