### ISSUE TITLE
Zipfile extraction fails

### ISSUE THREAD

**Issue by stellarhoof** [miyakogi/pyppeteer#152]
When a file that's being extracted is already present in the target directory, https://github.com/miyakogi/pyppeteer/blob/dev/pyppeteer/chromium_downloader.py#L125 fails. Would it be possible to recursively delete the download path beforehand?

**Comment by miyakogi** [comment]
Are you calling `launch` from multi thread or multi process?
If so, safer workaround is to call `pyppeteer.commands.install` in main process before calling `launch` from multi process.

Checking existence of unzipped file before unzip may cause race condition in parallel process.

**Comment by stellarhoof** [comment]
We aren't using thread or process pool, but we are running our scripts in parallel, which causes race conditions on install. Closing this as it's a problem on our end.
