### ISSUE TITLE
chrome stuck after open some urls

### ISSUE THREAD

**Issue by MemoryAndDream** [miyakogi/pyppeteer#167]
Windows7 python3.5 pyppeteer 0.0.0.25
I use pyppeteer to deal with https://www.tmall.com/ ,but after open some pages the chrome stuck forever until I kill the python process.

**Comment by MemoryAndDream** [comment]
`
browser = await pyppeteer.launch({'headless': False,'args': ['--no-sandbox'],'devtools':True});  、

page = await browser.newPage();  

await page.goto('https://www.tmall.com/');  
`  

Then I try to open some urls by manual, after open serveral urls(such as https://detail.tmall.com/item.htm?id=44945804433) it get stucked.

**Comment by MemoryAndDream** [comment]
I have find the problem. I need set 'dumpio':True in launch,or subprocess.Popen chrome will be stuck if the stderr is too large!  Why don't set 'dumpio':True as default?

**Comment by 444851265** [comment]
Thank you very much. It solved a big problem for me.

**Comment by sertraline** [comment]
solved for me, thank you.
