### ISSUE TITLE
Custom Chrome binary

### ISSUE THREAD

**Issue by stellarhoof** [miyakogi/pyppeteer#186]
It'd be great if we could use our own custom chrome binary `PYPPETEER_CHROME_BINARY`? It might appear as if it's not needed but consider the case where pyppeteer is ran in an isolated environment where chrome is being installed as part of this "stripped-down" environment.

**Comment by nurettin** [comment]
This is already possible. See sources for the launch function:

```
opts = { "executablePath": "/your/custom/chrome" }
browser = await launch(opts)
```

**Comment by stellarhoof** [comment]
Thanks
