### ISSUE TITLE
RuntimeWarning: coroutine 'Browser.close' was never awaited

### ISSUE THREAD

**Issue by jamcplusplus** [miyakogi/pyppeteer#20]
I just run the demo. And it takes a bug.
```python
import asyncio
from pyppeteer.launcher import launch

async def main(browser):
    page = await browser.newPage()
    await page.goto('http://example.com')
    await page.screenshot({'path': 'example.png'})

    dimensions = await page.evaluate('''() => {
        return {
            width: document.documentElement.clientWidth,
            height: document.documentElement.clientHeight,
            deviceScaleFactor: window.devicePixelRatio,
        }
    }''')

    print(dimensions)
browser = launch(
    executablePath="/Applications/Chromium.app/Contents/MacOS/Chromium")
asyncio.get_event_loop().run_until_complete(main(browser=browser))
browser.close()
```

the result is
```shell
$ python3 test.py
{'width': 800, 'height': 600, 'deviceScaleFactor': 1}
test.py:21: RuntimeWarning: coroutine 'Browser.close' was never awaited
  browser.close()
```

**Comment by jamcplusplus** [comment]
Python version 3.6.4
Chromium version 66.0.3335.0

**Comment by andreymeretsky** [comment]
`import asyncio
from pyppeteer.launcher import launch

async def main():
    browser = launch()

    page = await browser.newPage()
    await page.goto('http://example.com')
    await page.screenshot({'path': 'example.png'})

    dimensions = await page.evaluate('''() => {
        return {
            width: document.documentElement.clientWidth,
            height: document.documentElement.clientHeight,
            deviceScaleFactor: window.devicePixelRatio,
        }
    }''')
    await browser.close()

    print(dimensions)
asyncio.get_event_loop().run_until_complete(main())
`
I put browser in the main func (as in README) but there is another error appeares (

**Comment by miyakogi** [comment]
Updated sample code.

**Comment by jamcplusplus** [comment]
thanks~
