### ISSUE TITLE
Is there a way to scroll to end of page in pyppeteer

### ISSUE THREAD

**Issue by aidataguy** [miyakogi/pyppeteer#205]
I have tried looking in documentation and such, but not able to find a way to scroll down to bottom of page while using pyppeteer library with python3. 

Would be great if anyone could point me to the right direction or solution.

**Comment by srkn** [comment]
Maybe too late but this will work
`await page.evaluate("""{window.scrollBy(0, document.body.scrollHeight);}""")`

**Comment by aidataguy** [comment]
@srkn that worked great!! thanks!
