### ISSUE TITLE
Request.resourceType never populated

### ISSUE THREAD

**Issue by cnicodeme** [miyakogi/pyppeteer#27]
The `resourceType` parameter from the network_manager.Request is never populated.

@see https://github.com/miyakogi/pyppeteer/blob/dev/pyppeteer/network_manager.py#L285

**Comment by cheng10** [comment]
fixed @ 5969c1

**Comment by miyakogi** [comment]
Thank you for reporting issue.
Now its fixed.

**Comment by cnicodeme** [comment]
Awesome, if I find anything else, I'll report them :)

Good job on the library!
