### ISSUE TITLE
Closing an non connected instance generate an exception

### ISSUE THREAD

**Issue by cnicodeme** [miyakogi/pyppeteer#28]
Hi,

Here's an issue:

```
    instance = launch(headless=True)
    instance.close()
```

`.close()` should check if the connection is active before trying to close the connection :)

**Comment by miyakogi** [comment]
Thank you for reporting.
Fixed by https://github.com/miyakogi/pyppeteer/commit/4e800020dac3bddeede4fc052c12a828cc1cc62c

**Comment by cnicodeme** [comment]
You're fast!! Thank you :)
