### ISSUE TITLE
Page.cookies() returns List, not Dict

### ISSUE THREAD

**Issue by grammy-jiang** [miyakogi/pyppeteer#281]
I just notice the method [Page.cookies()](https://miyakogi.github.io/pyppeteer/reference.html#pyppeteer.page.Page.cookies) returns List, not Dict.

Maybe the typing hint for this method should be fixed.

**Comment by Mattwmaster58** [comment]
Hi @grammy-jiang , it looks like this project has been abandoned. You may want to consider the active fork [pyppeteer2](https://github.com/pyppeteer/pyppeteer2). Feel free to create an issue there if your problem persists with the updated library.
