### ISSUE TITLE
`from pyppeteer import launch` doesn't work on the documentation.

### ISSUE THREAD

**Issue by cnicodeme** [miyakogi/pyppeteer#30]
From the documentation located here:
https://github.com/miyakogi/pyppeteer#usage

The line
```from pyppeteer import launch```

doesn't work, it should be:
```from pyppeteer.launcher import launch```

**Comment by miyakogi** [comment]
Which version of pyppeteer are you using?
I think version 0.0.10 (pypi's latest version) can import `launch` from `pyppeteer` package.

**Comment by cnicodeme** [comment]
Oh yes, my bad, I'm on 0.0.9! I'll update it. Thanks
