### ISSUE TITLE
Complete noob question

### ISSUE THREAD

**Issue by taewookim** [miyakogi/pyppeteer#39]
I've been using phantomjs (speaking of which.. is horrible to use with python), then i find this. Thank you @miyakogi 

Have some noob questions

1) How do you make sure that pyppeteer follow redirects?

2) how do you fetch list of links (along with innerHTML text of the links)

3) how do you fetch the PDF that's requested in header?

**Comment by miyakogi** [comment]
This library is just controlling chrome (chromium).
For the second case, using [requests-html](https://github.com/kennethreitz/requests-html), which wraps pyppeteer, will be better choice.
