### ISSUE TITLE
Proper naming of attributes

### ISSUE THREAD

**Issue by ichux** [miyakogi/pyppeteer#42]
@miyakogi 

I want to send a pull request, but, can I do some renaming of attributes as advised here: http://legacy.python.org/dev/peps/pep-0008/#prescriptive-naming-conventions e.g.

`self._ignoreHTTPSErrors` becomes `self._ignore_https_errors`

**Comment by miyakogi** [comment]
Pyppeteer is using same attribute names to puppeteer, in order to make it easy to find changes and to port code from puppeteer (JS) to pyppeteer (python).

Thank you for considering to send PR.
