### ISSUE TITLE
Puppeteer hangs for some websites (Navigation Timeout Exceeded: 30000 ms exceeded).

### ISSUE THREAD

**Issue by deinega** [miyakogi/pyppeteer#66]
Puppeteer hangs at some websites, throwing following error:
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 30000 ms exceeded.

This is the example:
```
async def main():
    browser = await launch({'headless': False})
    page = await browser.newPage()
    await page.goto('https://www.ferragamo.com/shop/us/en/women/silk-bijoux/shawls-and-stoles')
    await browser.close()
asyncio.get_event_loop().run_until_complete(main())
```

I have tried 'waitUntil': 'networkidle0', 'waitUntil': 'networkidle2'. It does not help for this particular website.

**Comment by FedorChervyakov** [comment]
You can use **timeout** kwarg with page.got to specify necessary timeout.
`page.goto(url, timeout=100000)`
I had similar issue, and I don't think it is a bug. I believe when you load a page, browser waits for all resources and content to load, and probably waits until functions set to run on page load finish execution.
