### ISSUE TITLE
Grab href value from anchor tags?

### ISSUE THREAD

**Issue by zdrouse** [miyakogi/pyppeteer#68]
Hello,

I'm having difficulty figuring out how I can grab href values from anchor tags using pyppeteer.

I'm able to find the ElementHandle of these anchor tags, but how am I supposed to get the href attribute?
Is this done using evaluate function from Page class?  I've tried many variations of grabbing the href attribute with no success.

```python
prize_url_element = await giveaway.xpath(
                '//a[@class="a-link-normal giveAwayItemDetails"]/@href'
)

prize_url = await ga_page.evaluate(
                '(prize_url_element) => prize_url_element.href',
                prize_url_element
)
```

Might be doing something wrong but maybe someone can help me out.

Thanks!

**Comment by Bruledamien** [comment]
Hi, this is just a supposition, but don't giveaway and ga_page have to be the same object ?

**Comment by zdrouse** [comment]
@Bruledamien I don't think so because I don't believe ElementHandle class has `evaluate()` function available to it.

In the case above, my `giveaway` variable is an ElementHandle that I am grabbing (the anchor tag that has href) and I am trying to get the value of the href (the url) and I assume I have to use the `ga_page` Page variable I am working with to evaluate the value of the ElementHandle.

**Comment by Bruledamien** [comment]
How are you defining giveaway ? Aren't you grabbing the element from the ga_page ?
Maybe this example can help you
https://github.com/GoogleChrome/puppeteer/issues/1838

**Comment by zdrouse** [comment]
@Bruledamien yes that's correct, `giveaway` is being grabbed from ga_page using xpath further above.  

It's actually a collection of giveaways, so I am iterating through each one, here is a stripped down version of more code I am using:
```python
giveaway_grid_selector = '#giveaway-grid'
giveaway_grid = await ga_page.querySelector(giveaway_grid_selector)
if giveaway_grid:
    page_giveaways = await giveaway_grid.xpath('*/*')
for giveaway in page_giveaways:
    prize_url_element = await giveaway.xpath(
                '//a[@class="a-link-normal giveAwayItemDetails"]/@href'
    )

    prize_url = await ga_page.evaluate(
                '(prize_url_element) => prize_url_element.href',
                prize_url_element
    )
    print(prize_url)
```

I'll try playing around with the issue you linked.

**Comment by zdrouse** [comment]
I figured it out.  And of course it was a simple discovery.

I didn't need to drill down any further with xpath, I found I can just use `giveaway` ElementHandle and just get the href right from that div:

```python
prize_href = await ga_page.evaluate(
                '(giveaway) => giveaway.href',
                giveaway
            )
print(prize_href)
```
