### ISSUE TITLE
How to press button whilst clicking (e.g. a link or element)?

### ISSUE THREAD

**Issue by iiLaurens** [miyakogi/pyppeteer#81]
Hi,

I am slightly confused by the whole asynchronous programming concept and it's application in pyppeteer. I was wondering if someone could help me out.

I thought of an example myself which would probably require correct asynchronous programming; having a function that clicks some location whilst holding control (i.e. to open the link in a new tab in chrome). The input functionality of pyppeteer both has a `Keyboard.press()` and `Mouse.click()` method. What I need is for the press down to be called (with proper delay), then have the click happen and have it finished with the press up after the delay is finished. Looking at the functions in [input.py](https://github.com/miyakogi/pyppeteer/blob/dev/pyppeteer/input.py)

How would one go about making such a function `press_and_click()` which applies the `Keyboard.press()` and `Mouse.click()` in a correct and asynchronous manner?

**Comment by rodjun** [comment]
https://miyakogi.github.io/pyppeteer/reference.html#pyppeteer.input.Keyboard.down
