### ISSUE TITLE
BrowserError: Failed to connect to browser port

### ISSUE THREAD

**Issue by FedorChervyakov** [miyakogi/pyppeteer#82]
I'm using ubuntu 18.04, and python 3.6.5. After the installation of pyppeteer, when I try to run simple example, at first pyppeteer downloads chrome, but then I get following error:
`
pyppeteer.errors.BrowserError: Failed to connect to browser port: http://127.0.0.1:54165/json/version
`
When I try to run chrome from ~/.pyppeteer/local-chromium/543305/chrome-linux I get this error:
`
./chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
`
Best Regards,
Fedor Chervyakov

**Comment by FedorChervyakov** [comment]
I was able to solve this issue by installing libraries with following command:
`
sudo apt-get install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
`
I found this solution in puppeteer repository here on GitHub. Here is the link to it https://github.com/GoogleChrome/puppeteer/issues/2462

**Comment by wizardyhnr** [comment]
Thanks, it fixed my problem.

It is possible to check missing libs on other distributions using "ldd" command.
