### ISSUE TITLE
安装出现 gbk 错误时的处理方法

### ISSUE THREAD

**Issue by midpoint** [miyakogi/pyppeteer#86]
在python 3.5 下安装出错，出错提示：

> d:\Python35\Scripts>d:\Python35\python.exe -m pip install pyppeteer
> Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
> Collecting pyppeteer
>   Downloading http://mirrors.aliyun.com/pypi/packages/46/0d/a136a3c2d04574051673582967348a60a9532547eca45e108c0f42313d1f/pyppeteer-0.0.17.tar.gz (1.2MB)
>     100% |████████████████████████████████| 1.2MB 25.7MB/s
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\midpoint\AppData\Local\Temp\pip-install-2w2qnc0o\pyppeteer\setup.py", line 27, in <module>
>         compile_files(in_dir, out_dir, target)
>       File "d:\Python35\lib\site-packages\py_backwards\compiler.py", line 85, in compile_files
>         dependencies.update(_compile_file(paths, target))
>       File "d:\Python35\lib\site-packages\py_backwards\compiler.py", line 57, in _compile_file
>         code = f.read()
>     UnicodeDecodeError: 'gbk' codec can't decode byte 0xb6 in position 2295: illegal multibyte sequence
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\midpoint\AppData\Local\Temp\pip-install-2w2qnc0o\pyppeteer\

打开文件“d:\Python35\lib\site-packages\py_backwards\compiler.py” 找到 57行，在open语句（有两处需要修改）中加入：encoding='UTF-8'

`
56：   with paths.input.open(encoding='UTF-8') as f:
57：        code = f.read()

71：    with paths.output.open('w',encoding='UTF-8') as f:
72：        f.write(transformed)
`
再安装就成功了：
python -m pip install -U git+https://github.com/miyakogi/pyppeteer.git@dev

**Comment by miyakogi** [comment]
Python 3.5 support is experimental and will be dropped later.
Please use python 3.6+.
