### ISSUE TITLE
When does the pyppeteer catch up with puppeteer v1.5.0?

### ISSUE THREAD

**Issue by tigerfsh** [miyakogi/pyppeteer#89]
request.redirectChain(new in v1.2.0) and request.isNavigationRequest(new in v1.5.0) are very useful in the situation when redirects are supposed to be intercepted.  any dev plan?

**Comment by miyakogi** [comment]
I'm sorry for slow catch up.

Now almost caught up v1.1 and will release soon.
Then I start catching up v1.2, but since v1.2 does not seem to include large changes, it would not take long time to catch up it.

I continue to catch up puppeteer, but I'm sorry I can't say when to catch up v1.5.

**Comment by tigerfsh** [comment]
Thanks for your reply.
