### ISSUE TITLE
Webpage to PDF

### ISSUE THREAD

**Issue by pavitrakumar78** [miyakogi/pyppeteer#9]
Hi,

Thanks for this port!

I was looking at the docs and it said `Page.pdf` feature is not yet implemented, do you have plans to complete that feature anytime soon?

**Comment by shulcsm** [comment]
I have not yet tried but seems to be implemented https://github.com/miyakogi/pyppeteer/blob/dev/pyppeteer/page.py#L586
Just a stray comment.

**Comment by pavitrakumar78** [comment]
@shulcsm Thanks for the update! I'll try it out!
