### ISSUE TITLE
Failed to connect to browser port

### ISSUE THREAD

**Issue by Elaoed** [miyakogi/pyppeteer#92]
I try to use pyppeteer on centos 7.2 with google-chrome-stable but below error was raised

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/local/python3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "test.py", line 6, in main
    browser = await launch({"executablePath": "/usr/bin/google-chrome-stable"})
  File "/usr/local/python3.6/lib/python3.6/site-packages/pyppeteer/launcher.py", line 243, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/python3.6/lib/python3.6/site-packages/pyppeteer/launcher.py", line 160, in launch
    self.browserWSEndpoint = self._get_ws_endpoint()
  File "/usr/local/python3.6/lib/python3.6/site-packages/pyppeteer/launcher.py", line 178, in _get_ws_endpoint
    raise BrowserError(f'Failed to connect to browser port: {url}')
pyppeteer.errors.BrowserError: Failed to connect to browser port: http://127.0.0.1:32776/json/version

python version: 3.6.5
pyppeteer: (0.0.17)
And I use google-chrome-stable --headless --screenshot --no-sandbox http://example.com it works

**Comment by Elaoed** [comment]
After add args "--no-sandbox" like this: browser = await launch({"executablePath": "/usr/bin/google-chrome-stable"}, args=['--no-sandbox'], headless=True) , it seems work but timeout error was raised : pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 12000 ms exceeded.

**Comment by miyakogi** [comment]
Was the timeout error raised when loading http://example.com?
Does it reproduce with longer timeout option?

**Comment by Elaoed** [comment]
Sorry. I tried a website with only some text, and it didn't timeout anymore. So i guess chome need time to execute js file. But i have a question more about encoding. some file words show in the screenshot are rectangle with X in it. Is there are any place that we can pass encoding as a parameter. like encoding=utf-8

**Comment by Elaoed** [comment]
Or it's a issue about font? 
<img width="169" alt="screen shot 2018-07-07 at 21 14 26" src="https://user-images.githubusercontent.com/24728831/42411211-c5493610-822a-11e8-8b46-e6b1779f4db8.png">

**Comment by miyakogi** [comment]
Is the page correctly rendered when accessed by chrome manually?

**Comment by Elaoed** [comment]
No... when i use google-chrome-stable in commandline to generate a screenshot of the website, the page is not correctly as well... So it's maybe a problem of google-chrome-stable command..

**Comment by miyakogi** [comment]
So it's not a pyppeteer's issue.

**Comment by Elaoed** [comment]
Yes， Thank you :)
