### ISSUE TITLE
capture click event

### ISSUE THREAD

**Issue by tigerfsh** [miyakogi/pyppeteer#95]
Hi, @miyakogi ,I have a problem with trigger event as in the following example.
~~~
<input id="test" onclick="alert('my gold.')" type="button" value="leave me alone" />
<input id="demo" type="button" value="Click Me!" />

<script type="text/javascript">
document.getElementById("demo").onclick=function(){
alert(this.getAttribute("type"));
</script>
~~~
I want to capture and triggering all the **click event**, and I find it difficult to detect whether the second **input** element has a click event or not by searching all the DOM elements, Can you give me a solution using pyppeteer?

**Comment by miyakogi** [comment]
Currently pyppeteer does not provide easy api for such purpose.

I'm not sure, but might be possible by using lower layer interface ([CDPSession](https://miyakogi.github.io/pyppeteer/reference.html#cdpsession-class)) and [DOMDebugger.getEventListeners](https://chromedevtools.github.io/devtools-protocol/tot/DOMDebugger/#method-getEventListeners) method of DevTools Protocol.
