### ISSUE TITLE
How to avoid jumping into a new page?

### ISSUE THREAD

**Issue by tigerfsh** [miyakogi/pyppeteer#97]
this is my code:
~~~
async def click(page, nodes, _max):
    index = 0

    while True:
        if index > _max:
            break

        await page.evaluate("""
        (nodes, index) => {
            try
            {
             nodes[index].click();
            }catch(err)
            {return "error";}

        }
        """, nodes, index)
        index += 1
~~~
In some page, the function will hang at **nodes[index].click();** when the url of the current page has changed.Is there a solution to avoid jumping into a new page(url changed)?

**Comment by miyakogi** [comment]
How about pressing `Ctrl` key during click?

See https://miyakogi.github.io/pyppeteer/reference.html#pyppeteer.input.Keyboard.down
